spring:
  application:
    name: flight-service
  cache:
    type: caffeine
    cache-names:
      - flights-all
      - flights
      - searchFlights
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=5m

server:
  port: 8081
